# golangci-lint configuration for azd-core
# Ensures consistent linting between local development and CI
# Requires golangci-lint v2.8.0+

version: "2"

linters:
  default: standard
  enable:
    - errcheck      # Check for unchecked errors
    - staticcheck   # Static analysis checks
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - unused        # Checks for unused code

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    staticcheck:
      checks: ["all"]
    govet:
      disable:
        - fieldalignment  # Too noisy for test structs

formatters:
  enable:
    - gofmt         # Checks if code is gofmt-ed
    - goimports     # Checks imports are formatted

issues:
  # Maximum issues count per one linter (0 = unlimited)
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text (0 = unlimited)
  max-same-issues: 0


